CREATE TABLE STORES_DETAILS(
id int not null primary key,
store_name varchar(255),
store_location varchar(255)
);

CREATE TABLE TIMINGS(
timings_id int not null primary key,
store_id int not null,
start_hour varchar(25),
end_hour varchar(25),
num_of_people int not null,
CONSTRAINT storeId_Fk FOREIGN KEY (store_id) REFERENCES STORES_DETAILS(id),
UNIQUE INDEX store_time_idx(store_id,start_hour,end_hour)
);



INSERT INTO STORES_DETAILS 
VALUES (1,'COSTCO','NEWARK DE 19702');
INSERT INTO STORES_DETAILS
VALUES (2,'FOOD LION','NEW CASTLE DE 19720');
INSERT INTO STORES_DETAILS
VALUES(3,'FOOD LION','NEWARK DE 19711');
INSERT INTO STORES_DETAILS
VALUES(4,'FOOD LION','WILMINGTON DE 19802');
INSERT INTO STORES_DETAILS
VALUES(5,'SHOPRITE','BRANDYWINE COMMONS II DE 19803');
INSERT INTO STORES_DETAILS
VALUES(6,'SHOPRITE','NEWARK DE 19713');
INSERT INTO STORES_DETAILS
VALUES(7,'SHOPRITE','BEAR DE 19701');
INSERT INTO STORES_DETAILS
VALUES(8,'SHOPRITE','CHRISTIANA CROSSING 19801');
INSERT INTO STORES_DETAILS
VALUES(9,'ACME','CONCORD PIKE DE 19803');
INSERT INTO STORES_DETAILS
VALUES(10,'ACME','BEAR DE 19701');
INSERT INTO STORES_DETAILS
VALUES(11,'ACME','MIDDLETOWN DE 19709');
INSERT INTO STORES_DETAILS
VALUES(12,'ACME','TROLLEY SQUARE 19806');

SELECT * FROM STORES_DETAILS;

DROP TABLE TIMINGS;

